source 'https://rubygems.org'
gem 'jekyll', '~> 3.7'
gem 'compass', '~> 1.0', '>= 1.0.3'
gem 's3_website', '~> 3.4'
gem 'rake', '~> 12.3'
gem 'sass', '~> 3', '< 3.5'
gem 'jekyll-compress-images', '~> 1.2'
